### ISSUE TITLE
Bad link for self-contained JAR

### ISSUE THREAD

**Issue by todrobbins** [tberg12/ocular#2]
http://www.cs.utexas.edu/~dhg/maven-repository/snapshots/edu/berkeley/cs/nlp/ocular/0.3-SNAPSHOT/ocular-0.3-SNAPSHOT-with_dependencies.jar does not resolve.

I get a `Not Found` error.

**Comment by dhgarrette** [comment]
Fixed.  Sorry about that.

**Comment by todrobbins** [comment]
PS: Although, I was able to build from source via https://github.com/tberg12/ocular#optional-building-ocular-from-source-code. 👍

**Comment by todrobbins** [comment]
Oh no worries! Thanks!
