### ISSUE TITLE
InitializeFont gives NullPointerException

### ISSUE THREAD

**Issue by jbingel** [tberg12/ocular#3]
I managed to train a language model, but get a NPE when trying to initialize the font model (step 2). I use the self-contained Jar (0.3-SNAPSHOT, downloaded 2 May 2016).

Error stacktrace is attached.
[npe.txt](https://github.com/tberg12/ocular/files/244875/npe.txt)

**Comment by juancobo** [comment]
I had the same problem, both when I used the jar supplied and also when building the jar from scratch. I was able to resolve it by changing the function declaration in line 57 of src/main/java/edu/berkeley/cs/nlp/ocular/main/InitializeFont.java to `public static void main(String[] args) {` and rebuilding the jar.

**Comment by dhgarrette** [comment]
This should be fixed now:

https://github.com/tberg12/ocular/blob/5d4d977208713c2504909a30136cb7ea3f2801ee/src/main/java/edu/berkeley/cs/nlp/ocular/main/InitializeFont.java#L57
