### ISSUE TITLE
Download Page for the self-contained jar is not found

### ISSUE THREAD

**Issue by pakdanan** [tberg12/ocular#6]
This page is not found: http://www.cs.utexas.edu/~dhg/maven-repository/snapshots/edu/berkeley/cs/nlp/ocular/0.3-SNAPSHOT/ocular-0.3-SNAPSHOT-with_dependencies.jar .
Thanks

**Comment by dhgarrette** [comment]
Looks like my old university account was deactivated.  I updated the link in the README to http://www.dhgarrette.com/maven-repository/snapshots/edu/berkeley/cs/nlp/ocular/0.3-SNAPSHOT/ocular-0.3-SNAPSHOT-with_dependencies.jar
